### ISSUE TITLE
jspm install: Installation changes not saved.

### ISSUE THREAD

**Issue by Miega** [Figedi/denon_remote#1]
Trying to run `jspm install` after I installed jspm on local and global scale, still get the following message:

     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Updating registry cache...

     warn Error on getOverride for jspm:npm
     Error: Command failed: C:\windows\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
     fatal: Unable to find remote helper for 'https'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

     warn Error on getOverride for jspm:npm
     Error: Command failed: C:\windows\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
     fatal: Unable to find remote helper for 'https'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

     warn Error on getOverride for jspm:npm
     Error: Command failed: C:\windows\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
     fatal: Unable to find remote helper for 'https'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

     warn Installation changes not saved.

Any assistance would be helpful.

**Comment by Figedi** [comment]
Hmm this looks like a jspm issue not directly related to my project. Some googling said there isnt any curl module available. That was for linux though, so I'm guessing its something comparable in Windows. Have you checked whether jspm works in an isolated project? (e.g. create some dummy project)
